# Generated by Django 3.0.6 on 2020-05-16 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('nric', models.CharField(max_length=9, null=True, verbose_name='NRIC')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of Birth')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='GuildWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=200)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Guild')),
            ],
        ),
    ]
